### ISSUE TITLE
how to handle global modifiers?

### ISSUE THREAD

**Issue by adi-works** [franzheidl/bemify#12]
I was able to get it working, but the necessary syntax proves cumbersome. E.g.:
```
@include element ('item') {
    @include state (error, has) {
        // * issue starts here, where output should be `.form__item-error`
        @include block ('form') { // * how to achieve the above without this line?
            @include element ('item-error') {
                display: block;
            }
        }
    }
}
```

**Comment by franzheidl** [comment]
Hi,

I assume what you're trying to achive is `.item.has-error .form__item-error`, right?

A couple of things don’t quite work here IMO:

You’re trying to use an `element` as your base level selector, but an `element` will only ever exist inside a `block`, since BEM relies on Blocks that are parents of elements / subject of modifiers, so this does not adhere to BEM.

Bemify requires the `@element`, `@modifier`, and `@state` mixins to be used in the context of a `@block` mixin so it can re-use the selector of the `@block` (that’s actually its main purpose, and that's the way BEM works), so your code should break (it does break for me) and throw an error `Base-level rules cannot contain the parent-selector-referencing character '&'`.



However, I realize scoping is sometimes necessary in the real world , so you could technically use a block as your base rule:

```
@include block ('item') {
    @include state (error, has) {
        @include block ('form') { 
            @include element ('item-error') {
                display: block;
            }
        }
    }
}
```


**BUT** what you’re trying is to scope a block (define `.form__item-error` in the context of `.item.has-error`). Generally (and this might be subject to argument), scoping is regarded as a bad practice when it comes to BEM, as the basic idea of a block is to be self-enclosed and self-defining, and only to be modified by modifiers on the block itself, not by scopes (also, scoping increases specificity which you generally want to avoid using BEM).

I’d advise against defining blocks in the scope of another block, and try one of the following approaches: 

If the (child) `block` only exists in the scope of the (parent) `block`, it should actually be an `element`.

If you are really only modifying the (child) `block`in the context of the parent, but define it somewhere else, you could:

1. Use a modifier on the (child) `block` itself instead of a scope,   this would be „true“ BEM and not increase specificity, so all in all the cleaner solution.

2. You could use the above solution of using `@block`at the base, though I would recommend to pull the (child) `block` out of the bemify chain, and simply use a dedicated source file per modifier (assuming you have a reasonable amount of modifiers in you project) which works simply like this:

```
.has-error {
    @include block ('form') {
        @include element ('item-error') {
            display: block;
        }
    }
}
```
This is much easier to read, and you are not declaring blocks inside blocks (also, I think `.item` on the base is not really needed here, it only increases specificity). There really is no need to use bemify for scoping, as bemify is designed to make your code more idiomatic form a BEM perspective, and defining blocks inside blocks just is not idiomatic BEM in my book.

I don’t know what stack you are using, with many modern frameworks (like React) you would only ever render a `.form__item-error` element if there actually was an error and you would not need any scoping at all.

I hope this helps.

**Comment by adi-works** [comment]
Sweet. My bad for leaving out the code that encapsulates the `item` element. It's, as you might guessed, a `form` block. So in that regard, it does follow BEM. I'll re-consider scoping.

**Comment by franzheidl** [comment]
Hmm, you could have saved me quite a bit of time here by posting your complete code… 
Anyway, my comment still stands regarding nesting blocks, yes, please re-consider scoping.
